steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello', 'cloud-run' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'hello', '--image', 'gcr.io/$PROJECT_ID/hello', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/hello'
